### PR TITLE
Fix: Added GPG Key for Kubernetes Repo

### PR DESCRIPTION
**Pull request by LearningEntity**
Hey,
when running the kubectl role, the repository cant be added because there is no gpg-key added. My fix solved this issue on my machine.

### CODE REVIEW

**Comment by BaldFabi** [comment]
You're correct but you should use the module `apt_key` to retrieve and add the key

**Comment by LearningEntity** [comment]
Added key adding with apt_key.

**Comment by BaldFabi** [comment]
`state:` can be omitted if the value is `present` and the roles shouldn't be commented out 😉

**Comment by LearningEntity** [comment]
Done!

**Pull request merged**
